apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sharycar-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharycar-auth
  template:
    metadata:
      labels:
        app: sharycar-auth
    spec:
      containers:
      - name: sharycar-authenticetion-container
        image: jkrajnc11/sharycar-microservice-authentication
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: sharycar-auth-lb
spec:
  type: LoadBalancer
  selector:
    app: sharycar-auth
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
