apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sharycar-pickup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharycar-pickup
  template:
    metadata:
      labels:
        app: sharycar-pickup
    spec:
      containers:
      - name: sharycar-pickup-container
        image: jkrajnc11/sharycar-microservice-pickup
        ports:
        - containerPort: 8084
        
---
apiVersion: v1
kind: Service
metadata:
  name: sharycar-pickup-lb
spec:
  type: LoadBalancer
  selector:
    app: sharycar-pickup
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8084
